/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsAiDevtoolRouteImport } from './routes/projects/ai-devtool'
import { Route as ProjectsExpenseTrackerRouteImport } from './routes/projects/expense-tracker'
import { Route as ProjectsTaskWorkspaceRouteImport } from './routes/projects/task-workspace'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsAiDevtoolRoute = ProjectsAiDevtoolRouteImport.update({
  id: '/projects/ai-devtool',
  path: '/projects/ai-devtool',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsExpenseTrackerRoute = ProjectsExpenseTrackerRouteImport.update({
  id: '/projects/expense-tracker',
  path: '/projects/expense-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsTaskWorkspaceRoute = ProjectsTaskWorkspaceRouteImport.update({
  id: '/projects/task-workspace',
  path: '/projects/task-workspace',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/ai-devtool': typeof ProjectsAiDevtoolRoute
  '/projects/expense-tracker': typeof ProjectsExpenseTrackerRoute
  '/projects/task-workspace': typeof ProjectsTaskWorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/ai-devtool': typeof ProjectsAiDevtoolRoute
  '/projects/expense-tracker': typeof ProjectsExpenseTrackerRoute
  '/projects/task-workspace': typeof ProjectsTaskWorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/ai-devtool': typeof ProjectsAiDevtoolRoute
  '/projects/expense-tracker': typeof ProjectsExpenseTrackerRoute
  '/projects/task-workspace': typeof ProjectsTaskWorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/ai-devtool'
    | '/projects/expense-tracker'
    | '/projects/task-workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects/ai-devtool'
    | '/projects/expense-tracker'
    | '/projects/task-workspace'
  id:
    | '__root__'
    | '/'
    | '/projects/ai-devtool'
    | '/projects/expense-tracker'
    | '/projects/task-workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsAiDevtoolRoute: typeof ProjectsAiDevtoolRoute
  ProjectsExpenseTrackerRoute: typeof ProjectsExpenseTrackerRoute
  ProjectsTaskWorkspaceRoute: typeof ProjectsTaskWorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/ai-devtool': {
      id: '/projects/ai-devtool'
      path: '/projects/ai-devtool'
      fullPath: '/projects/ai-devtool'
      preLoaderRoute: typeof ProjectsAiDevtoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/expense-tracker': {
      id: '/projects/expense-tracker'
      path: '/projects/expense-tracker'
      fullPath: '/projects/expense-tracker'
      preLoaderRoute: typeof ProjectsExpenseTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/task-workspace': {
      id: '/projects/task-workspace'
      path: '/projects/task-workspace'
      fullPath: '/projects/task-workspace'
      preLoaderRoute: typeof ProjectsTaskWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsAiDevtoolRoute: ProjectsAiDevtoolRoute,
  ProjectsExpenseTrackerRoute: ProjectsExpenseTrackerRoute,
  ProjectsTaskWorkspaceRoute: ProjectsTaskWorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
